> ## numpy --> 
    1.numpy is used to perform all operation for array
    2. we can store only number inside the array
    

In [2]:
import numpy as np 

list has ","
but the  array does not have the ","

In [1]:
l = [1,2,3,6,55,8,9] # list 

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[ 1  2  3  6 55  8  9]


In [9]:
arr.ndim

1

In [14]:
array1 = np.array([[1,2,3]])

In [15]:
array1.ndim

2

In [17]:
array3 = np.array([[1,2,3],[2,6,56],[2,56,5]])

In [19]:
array3

array([[ 1,  2,  3],
       [ 2,  6, 56],
       [ 2, 56,  5]])

> # ndim ( number of rows , number of column)

In [18]:
array3.ndim

2

In [26]:
array4 = np.array([[[1,2],[2,6]]]) # three square bracket then 3 dimension 

In [27]:
array4.ndim

3

In [28]:
array5 = np.array([[[1,2],[2,6]]])

In [30]:
array5.shape

(1, 2, 2)

In [33]:
arr.ndim

1

In [31]:
arr.shape

(7,)

> # arange ---> 
    just like range 
    creat a array with in  given range
    (start , end+1)


In [34]:
a= np.arange(1,12)

In [36]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
type(a)

numpy.ndarray

In [46]:
b = np.arange(1,101)

In [47]:
b

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

> # linspace
    random numbers from give range of number 
    (start , end+1 , count of random number)
    it dives the data points in same intervels as given 
    (1,101,20) from 1 to  100 numbers it will dide that in 20 equal number and gives that 20 numbers to us 

In [2]:
import numpy as np 
b = np.linspace(1,101,20)

In [3]:
b 

array([  1.        ,   6.26315789,  11.52631579,  16.78947368,
        22.05263158,  27.31578947,  32.57894737,  37.84210526,
        43.10526316,  48.36842105,  53.63157895,  58.89473684,
        64.15789474,  69.42105263,  74.68421053,  79.94736842,
        85.21052632,  90.47368421,  95.73684211, 101.        ])

In [52]:
c = np.linspace(1,5,100)

In [53]:
c

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

> # reshape -- > 
    change the shape from 1 dimension to 2 or multiple dimension 
    (dim count , number of element in every dim)
    (x,y) == x*y this must equal to to {total number of data points}

In [54]:
x = np.arange(1,11)

In [55]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [57]:
x.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

> # ravel --> 
    convet any dimension array into one dimension 

In [60]:
o = np.array([[2,5,3],[2,5,6]])

In [67]:
copy = o.reshape(1,6) # we can not use reshape 

In [65]:
copy.ndim

2

In [66]:
o.ravel()

array([2, 5, 3, 2, 5, 6])

> # flatten 
same as ravel

In [68]:
n = np.array([[2,5],[2,6],[5,9],[5,9],[5,7]])

In [70]:
n.flatten()

array([2, 5, 2, 6, 5, 9, 5, 9, 5, 7])

> # transpose 
    row to col
    col to rows 
    conversion 

In [71]:
n.transpose()

array([[2, 2, 5, 5, 5],
       [5, 6, 9, 9, 7]])

> # add 
    add the first element of the array to frist elemt of another array element

In [75]:
o =np.array([[2,3],[3,2]])
m = np.array([[2,5],[6,8]])

In [76]:
np.add(o,m)

array([[ 4,  8],
       [ 9, 10]])

> # min 
    find the mimimum number from the array 
    axis = 1 -- > colum which is min
    axis = 0 -->  row which is min
    default axis is  0
    if same number then first occur one will be choose 

In [77]:
o =np.array([[2,3],[3,2]])

In [78]:
o.min()

2

> # max 
    find the maximum number from the array

In [79]:
o =np.array([[2,3],[3,2]])

In [80]:
o.max()

3

> # argmax -- > 
    return the index of max number from the array 

In [81]:
o =np.array([[2,3],[3,2]])

In [82]:
o.argmax()

1

> # argmin--> 
    return the index of min value from the array 

In [85]:
o =np.array([[22,31],[30,2]])

In [86]:
o.argmin()

3

arange()

> # slising

In [88]:
a = np.arange(1,11)

In [89]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
a[1:5]

array([2, 3, 4, 5])

In [93]:
a.min()

1

> # mean 

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
a.mean()

5.5

> # median 

In [6]:
np.median(a)

5.5

> # quartiles 

In [14]:
q1 = np.quantile(a,0.25)

In [15]:
q2 = np.quantile(a,0.50)

In [16]:
q3 = np.quantile(a,0.75)

## iqr -- inter quartile range

In [17]:
iqr = q3 -q1 
print(f"IQR is {iqr}")

IQR is 4.5


In [18]:
lower_range = q1 - 1.5*iqr
upper_range = q3 + 1.5*iqr

In [19]:
print(f"lower range will be{lower_range}")
print(f"upper_range will be {upper_range}")

lower range will be-3.5
upper_range will be 14.5


below and above this all the values will be otliers 

In [20]:
a = np.arange(11,21)

In [21]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
b = a.reshape(5,2)

In [25]:
b > 15

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

> # boolean indexing

### values greater than 15

In [26]:
b[b<15]

array([11, 12, 13, 14])

### even number from tha array

In [27]:
b[b%2==0]

array([12, 14, 16, 18, 20])

> # Math Function 
    
    

 > ## sin , cos  , tan and other trigno term
    π = 180 degree
    π/2 = 90 
    π/4 = 45
    π/ 6 = 30
    π/4 = 60 
    These anglesa re given in the terms of radians 
    these degrees are subtituted by this pi  concept and the way of writing is 
    np.pi == 180  and  np.pi == π

In [28]:
np.sin(np.pi) # sin(180)

1.2246467991473532e-16

In [31]:
np.sin((np.pi)/2)  # SIN(90)

1.0

> ## exponational values  , log 

In [32]:
print(np.e)

2.718281828459045


In [36]:
print(np.log(10))

2.302585092994046


In [40]:
print(np.log10(10)) # log 10 to the base 10

1.0


In [42]:
print(np.log(np.e))  # natural log  log e base to e 
# base and value if are same then they are same 

1.0


> ## square root 

In [43]:
print(np.sqrt(144))

12.0


> # questions 
    why numpy array is better than the python list 
    what is brodcasting
    difference between list and array




> # why numpy array is better than the python list
    + They use less memory than Python lists
    + Operations can be applied to entire arrays at once, avoiding the need for explicit loops and improving performance
    +  NumPy array is pretty fast in terms of execution, as compared to lists in Python.
    +

> # what is brodcasting 
     NumPy supports broadcasting, which allows operations between arrays of different shapes and sizes. This feature simplifies operations and enhances code readability.

     Broadcasting in NumPy is like extending smaller arrays to match the shape of larger arrays, so you can perform operations on them. Imagine you have two arrays, one is a column vector [1, 2, 3] and the other is a single number 2. Normally, you couldn't just add them together because they don't have the same shape. But with broadcasting, NumPy automatically extends the smaller array to match the shape of the larger one, so you can add them together like this:

> #  difference between list and array 